import { useEffect, useState } from "react";
import { startInterview, submitInterview, startPractice, submitPractice } from "../services/api";
import DashboardLayout from "./dashboard-layout";
import { Button } from "./ui/button";
import { Card, CardContent } from "./ui/card";
import { CircularProgress } from "./ui/circular-progress";
import { QuizLoader } from "./loading/quiz-loader";
import { useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import { fadeUp } from "../utils/animation-variants";
import { useTheme } from "../contexts/theme-context";

// ─── Mode Selection Screen ────────────────────────────────────────────────────
function ModeSelection({ onSelect, isDark }) {
  const textPrimary = isDark ? "#F1F5F9" : "#0F172A";
  const textSecondary = isDark ? "#CBD5E1" : "#475569";
  const cardBg = isDark ? "#111827" : "#FFFFFF";
  const borderColor = isDark ? "#334155" : "#E2E8F0";

  const modes = [
    {
      id: "dsa",
      title: "DSA Practice",
      subtitle: "MCQ Questions",
      description: "Answer 5 curated DSA multiple-choice questions on Arrays, Trees, Graphs, DP, Sorting and more. No resume required.",
      icon: (
        <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 3H5a2 2 0 00-2 2v4m6-6h10a2 2 0 012 2v4M9 3v18m0 0h10a2 2 0 002-2V9M9 21H5a2 2 0 01-2-2V9m0 0h18" />
        </svg>
      ),
      accent: "#4F46E5",
      accentBg: isDark ? "rgba(79,70,229,0.15)" : "#EEF2FF",
      badge: "No resume needed",
      badgeBg: "#ECFDF5",
      badgeColor: "#16A34A",
    },
    {
      id: "interview",
      title: "AI Interview",
      subtitle: "Resume-Based",
      description: "Get personalized interview questions generated by AI based on your uploaded resume and experience.",
      icon: (
        <svg className="w-8 h-8" fill="none" viewBox="0 0 24 24" stroke="currentColor">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9.75 17L9 20l-1 1h8l-1-1-.75-3M3 13h18M5 17H3a2 2 0 01-2-2V5a2 2 0 012-2h14a2 2 0 012 2v10a2 2 0 01-2 2h-2" />
        </svg>
      ),
      accent: "#7C3AED",
      accentBg: isDark ? "rgba(124,58,237,0.15)" : "#F5F3FF",
      badge: "Resume required",
      badgeBg: "#FEF3C7",
      badgeColor: "#D97706",
    },
  ];

  return (
    <DashboardLayout role="candidate">
      <div className="mx-auto max-w-3xl space-y-10">
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.5 }}
        >
          <h1 className="text-[32px] font-bold" style={{ color: textPrimary }}>
            Choose Practice <span style={{ color: "#4F46E5" }}>Mode</span>
          </h1>
          <p className="mt-2 text-lg" style={{ color: textSecondary }}>
            Select how you want to practice today
          </p>
        </motion.div>

        <div className="grid gap-6 sm:grid-cols-2">
          {modes.map((mode, idx) => (
            <motion.div
              key={mode.id}
              initial={{ opacity: 0, y: 24 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: idx * 0.1 + 0.2 }}
            >
              <button
                onClick={() => onSelect(mode.id)}
                className="w-full text-left rounded-2xl border-2 p-6 transition-all duration-200 hover:-translate-y-1 hover:shadow-lg focus:outline-none"
                style={{
                  borderColor,
                  backgroundColor: cardBg,
                  boxShadow: isDark ? "0 4px 16px rgba(0,0,0,0.3)" : "0 4px 16px rgba(0,0,0,0.04)",
                }}
                onMouseEnter={(e) => {
                  e.currentTarget.style.borderColor = mode.accent;
                }}
                onMouseLeave={(e) => {
                  e.currentTarget.style.borderColor = borderColor;
                }}
              >
                <div className="space-y-5">
                  <div
                    className="flex h-14 w-14 items-center justify-center rounded-xl"
                    style={{ backgroundColor: mode.accentBg, color: mode.accent }}
                  >
                    {mode.icon}
                  </div>

                  <div>
                    <div className="flex items-center gap-2 mb-1">
                      <h3 className="text-xl font-bold" style={{ color: textPrimary }}>
                        {mode.title}
                      </h3>
                      <span
                        className="rounded-full px-2 py-0.5 text-xs font-semibold"
                        style={{ backgroundColor: mode.accentBg, color: mode.accent }}
                      >
                        {mode.subtitle}
                      </span>
                    </div>
                    <p className="text-sm leading-relaxed" style={{ color: textSecondary }}>
                      {mode.description}
                    </p>
                  </div>

                  <div className="flex items-center justify-between">
                    <span
                      className="rounded-full px-3 py-1 text-xs font-semibold"
                      style={{ backgroundColor: mode.badgeBg, color: mode.badgeColor }}
                    >
                      {mode.badge}
                    </span>
                    <div
                      className="flex h-8 w-8 items-center justify-center rounded-full"
                      style={{ backgroundColor: mode.accentBg, color: mode.accent }}
                    >
                      <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                      </svg>
                    </div>
                  </div>
                </div>
              </button>
            </motion.div>
          ))}
        </div>
      </div>
    </DashboardLayout>
  );
}

// ─── Main Quiz Component ──────────────────────────────────────────────────────
export default function InterviewPractice() {
  const [mode, setMode] = useState(null); // null = show selection, "dsa" or "interview"
  const [questions, setQuestions] = useState([]);
  const [answers, setAnswers] = useState([]);
  const [current, setCurrent] = useState(0);
  const [sessionId, setSessionId] = useState(null); // used for both interviewId and practice sessionId
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const { theme } = useTheme();
  const isDark = theme === "dark";
  const navigate = useNavigate();

  const textPrimary = isDark ? "#F1F5F9" : "#0F172A";
  const textSecondary = isDark ? "#CBD5E1" : "#475569";
  const textMuted = isDark ? "#94A3B8" : "#64748B";
  const cardBg = isDark ? "#111827" : "#FFFFFF";
  const borderColor = isDark ? "#334155" : "#E2E8F0";

  // Load questions when mode is selected
  useEffect(() => {
    if (!mode) return;

    async function loadSession() {
      setLoading(true);
      setError(null);
      try {
        if (mode === "dsa") {
          const res = await startPractice();
          const qs = res.data.questions;
          if (!qs || qs.length === 0) throw new Error("No questions returned");
          setQuestions(qs);
          setSessionId(res.data.sessionId);
          setAnswers(new Array(qs.length).fill(null));
        } else {
          const res = await startInterview();
          const qs = res.data.questions;
          if (!qs || qs.length === 0) throw new Error("No questions returned from server");
          setQuestions(qs);
          setSessionId(res.data.interviewId);
          setAnswers(new Array(qs.length).fill(null));
        }
      } catch (err) {
        const errorMsg = err.response?.data?.message || err.message || "Failed to start session";
        setError(errorMsg);
      } finally {
        setLoading(false);
      }
    }

    loadSession();
  }, [mode]);

  // Keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (loading || !questions.length) return;

      if (["1", "2", "3", "4"].includes(e.key)) {
        const index = parseInt(e.key) - 1;
        if (index < questions[current].options.length) {
          const copy = [...answers];
          copy[current] = index;
          setAnswers(copy);
        }
      }
      if (e.key === "ArrowRight" && answers[current] !== null && current < questions.length - 1) {
        setCurrent((c) => c + 1);
      }
      if (e.key === "ArrowLeft" && current > 0) {
        setCurrent((c) => c - 1);
      }
    };

    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, [loading, questions, current, answers]);

  // ── Mode selection screen ──
  if (!mode) {
    return <ModeSelection onSelect={setMode} isDark={isDark} />;
  }

  // ── Loading ──
  if (loading) {
    return (
      <DashboardLayout role="candidate">
        <QuizLoader />
      </DashboardLayout>
    );
  }

  // ── Error ──
  if (error) {
    return (
      <DashboardLayout role="candidate">
        <div className="mx-auto max-w-xl">
          <Card className="border-destructive/50 bg-destructive/5">
            <CardContent className="pt-6 text-center space-y-4">
              <div className="text-4xl">⚠️</div>
              <p className="text-destructive font-medium">{error}</p>
              <div className="flex gap-3 justify-center">
                {mode === "interview" && (
                  <Button onClick={() => navigate("/upload")}>Upload Resume</Button>
                )}
                <Button variant="outline" onClick={() => { setMode(null); setError(null); }}>
                  Back to Selection
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </DashboardLayout>
    );
  }

  // ── No questions ──
  if (!questions || questions.length === 0) {
    return (
      <DashboardLayout role="candidate">
        <div className="text-center" style={{ color: textSecondary }}>
          No questions available right now.
        </div>
      </DashboardLayout>
    );
  }

  const question = questions[current];
  const progress = ((current + 1) / questions.length) * 100;

  const handleSubmit = async () => {
    try {
      let res;
      if (mode === "dsa") {
        res = await submitPractice(sessionId, answers);
      } else {
        res = await submitInterview(sessionId, answers);
      }

      const totalQ = questions.length;
      const serverScore = typeof res.data.score === "number"
        ? res.data.score
        : typeof res.data.overallScore === "number"
          ? res.data.overallScore
          : 0;
      const correctCount =
        typeof res.data.correctAnswers === "number"
          ? res.data.correctAnswers
          : Math.round((serverScore / 100) * totalQ);
      const accuracy = typeof res.data.accuracyPercentage === "number"
        ? res.data.accuracyPercentage
        : serverScore;

      navigate("/completion", {
        state: {
          score: serverScore,
          totalQuestions: totalQ,
          correctAnswers: correctCount,
          accuracyPercentage: accuracy,
          mode,
        },
      });
    } catch (err) {
      console.error("Submission failed", err);
      navigate("/candidate/dashboard");
    }
  };

  const modeLabel = mode === "dsa" ? "DSA Practice" : "AI Interview";
  const modeColor = mode === "dsa" ? "#4F46E5" : "#7C3AED";

  return (
    <DashboardLayout role="candidate">
      <div className="mx-auto max-w-4xl space-y-8 relative z-10">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <div className="flex items-center gap-3 mb-1">
              <button
                onClick={() => { setMode(null); setQuestions([]); setCurrent(0); setAnswers([]); setError(null); }}
                className="text-sm font-medium flex items-center gap-1 hover:opacity-80 transition-opacity"
                style={{ color: textMuted }}
              >
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                </svg>
                Change mode
              </button>
              <span
                className="rounded-full px-3 py-1 text-xs font-semibold"
                style={{ backgroundColor: isDark ? "rgba(79,70,229,0.22)" : "#EEF2FF", color: modeColor }}
              >
                {modeLabel}
              </span>
            </div>
            <h1 className="text-[32px] font-bold" style={{ color: textPrimary }}>
              Interview <span style={{ color: modeColor }}>Practice</span>
            </h1>
            <p style={{ color: textSecondary }}>
              Question {current + 1} of {questions.length}
            </p>
          </div>
          <div className="flex items-center gap-4">
            <div className="text-right">
              <p className="text-sm font-semibold" style={{ color: textPrimary }}>{Math.round(progress)}%</p>
              <p className="text-xs" style={{ color: textMuted }}>Completed</p>
            </div>
            <CircularProgress
              value={progress}
              size={50}
              strokeWidth={4}
              showValue={false}
              variant="royal"
            />
          </div>
        </div>

        {/* Question Card */}
        <AnimatePresence mode="wait">
          <motion.div
            key={current}
            variants={fadeUp}
            initial="initial"
            animate="animate"
            exit="exit"
          >
            <div
              className="flex min-h-[400px] flex-col rounded-xl border p-8 shadow-[0_4px_16px_rgba(0,0,0,0.04)]"
              style={{ borderColor, backgroundColor: cardBg }}
            >
              <div className="space-y-6 flex-1">
                <div className="flex items-center gap-2 flex-wrap">
                  <span
                    className="inline-block rounded-full border px-3 py-1 text-xs font-semibold"
                    style={{
                      backgroundColor: isDark ? "rgba(79,70,229,0.22)" : "#EEF2FF",
                      borderColor: isDark ? "rgba(79,70,229,0.35)" : "#C7D2FE",
                      color: "#4F46E5",
                    }}
                  >
                    {question.topic || "General"}
                  </span>
                  {question.difficulty && (
                    <span
                      className="inline-block rounded-full border px-3 py-1 text-xs font-semibold capitalize"
                      style={{
                        backgroundColor:
                          question.difficulty === "easy"
                            ? "#ECFDF5"
                            : question.difficulty === "medium"
                              ? "#FEF3C7"
                              : "#FEF2F2",
                        borderColor:
                          question.difficulty === "easy"
                            ? "#BBF7D0"
                            : question.difficulty === "medium"
                              ? "#FDE68A"
                              : "#FECACA",
                        color:
                          question.difficulty === "easy"
                            ? "#16A34A"
                            : question.difficulty === "medium"
                              ? "#D97706"
                              : "#DC2626",
                      }}
                    >
                      {question.difficulty}
                    </span>
                  )}
                </div>

                <h2 className="text-2xl font-medium leading-relaxed" style={{ color: textPrimary }}>
                  {question.question}
                </h2>

                <div className="grid gap-3 pt-4">
                  {question.options.map((opt, idx) => {
                    const isSelected = answers[current] === idx;
                    const optionStyle = isSelected
                      ? {
                        backgroundColor: isDark ? "rgba(79,70,229,0.18)" : "#EEF2FF",
                        borderColor: "#4F46E5",
                        color: textPrimary,
                        borderWidth: "2px",
                      }
                      : {
                        backgroundColor: cardBg,
                        borderColor,
                        color: textPrimary,
                        borderWidth: "1px",
                      };

                    return (
                      <motion.button
                        key={idx}
                        className="group relative w-full rounded-[10px] p-4 text-left transition-all duration-200"
                        style={optionStyle}
                        onClick={() => {
                          const copy = [...answers];
                          copy[current] = idx;
                          setAnswers(copy);
                        }}
                        whileHover={{ y: -2 }}
                        whileTap={{ scale: 0.98 }}
                        onMouseEnter={(e) => {
                          if (!isSelected) {
                            e.currentTarget.style.backgroundColor = isDark ? "#0F172A" : "#F8FAFC";
                            e.currentTarget.style.borderColor = isDark ? "#475569" : "#CBD5F5";
                          }
                        }}
                        onMouseLeave={(e) => {
                          if (!isSelected) {
                            e.currentTarget.style.backgroundColor = cardBg;
                            e.currentTarget.style.borderColor = borderColor;
                          }
                        }}
                      >
                        <div className="flex items-center gap-4">
                          <span
                            className="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg text-sm font-bold transition-all"
                            style={
                              isSelected
                                ? { backgroundColor: "#4F46E5", color: "#FFFFFF" }
                                : {
                                  backgroundColor: isDark ? "#0F172A" : "#F8FAFC",
                                  color: isDark ? "#CBD5E1" : "#475569",
                                  border: `1px solid ${borderColor}`,
                                }
                            }
                          >
                            {isSelected ? (
                              <svg className="w-5 h-5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                              </svg>
                            ) : (
                              idx + 1
                            )}
                          </span>
                          <span className="text-lg font-medium" style={{ color: textPrimary }}>
                            {opt}
                          </span>
                        </div>
                        <span
                          className="absolute right-4 top-1/2 -translate-y-1/2 rounded px-2 py-1 font-mono text-xs opacity-0 transition-opacity group-hover:opacity-100"
                          style={{
                            backgroundColor: isDark ? "#1F2937" : "#F1F5F9",
                            color: isDark ? "#94A3B8" : "#475569",
                          }}
                        >
                          {idx + 1}
                        </span>
                      </motion.button>
                    );
                  })}
                </div>
              </div>

              {/* Navigation */}
              <div className="mt-4 flex items-center justify-between border-t pt-8" style={{ borderColor }}>
                <Button
                  variant="outline"
                  onClick={() => setCurrent(current - 1)}
                  disabled={current === 0}
                  className="border font-semibold transition-all duration-200"
                  style={{ borderColor, backgroundColor: cardBg, color: textSecondary }}
                >
                  <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
                  </svg>
                  Previous
                </Button>

                <div className="flex items-center gap-2">
                  <span className="text-xs text-muted-foreground mr-2 hidden sm:inline-block">
                    Press{" "}
                    <kbd className="px-1.5 py-0.5 rounded bg-muted text-muted-foreground border border-border font-mono">
                      1–4
                    </kbd>{" "}
                    to select
                  </span>

                  {current < questions.length - 1 ? (
                    <Button
                      onClick={() => setCurrent(current + 1)}
                      disabled={answers[current] === null}
                      className="min-w-[140px] bg-indigo-600 text-white font-semibold transition-all duration-200 hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      Next Question
                      <svg className="w-4 h-4 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
                      </svg>
                    </Button>
                  ) : (
                    <Button
                      onClick={handleSubmit}
                      disabled={answers[current] === null}
                      className="min-w-[140px] bg-indigo-600 text-white font-semibold transition-all duration-200 hover:bg-indigo-700 disabled:opacity-50 disabled:cursor-not-allowed"
                    >
                      Finish Practice
                      <svg className="w-4 h-4 ml-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M5 13l4 4L19 7" />
                      </svg>
                    </Button>
                  )}
                </div>
              </div>
            </div>
          </motion.div>
        </AnimatePresence>

        {/* Progress dots */}
        <div className="flex justify-center gap-2 flex-wrap">
          {questions.map((_, idx) => (
            <button
              key={idx}
              onClick={() => setCurrent(idx)}
              className="w-2.5 h-2.5 rounded-full transition-all duration-200"
              style={{
                backgroundColor:
                  answers[idx] !== null
                    ? "#4F46E5"
                    : idx === current
                      ? isDark ? "#475569" : "#CBD5E1"
                      : isDark ? "#1F2937" : "#E2E8F0",
                transform: idx === current ? "scale(1.4)" : "scale(1)",
              }}
              title={`Question ${idx + 1}`}
            />
          ))}
        </div>
      </div>
    </DashboardLayout>
  );
}
